### ISSUE TITLE
Uncaught Exception on torrent search page.

### ISSUE THREAD

**Issue by shayneoneill** [FlixtorMe/FlixtorMe#25]
Error:
An uncaughtException was found
Error: incorrect header check
The program will end.

Steps to reproduce:
Download fresh copy of OSX Flixtor. Click on Torrent tab. Client crashes every time. 

Tried on two separate macs and Linux (Ubuntu 64bit latest) box. All three have same bug. The rest of the clients functionality works fine.

**Comment by sr-nu** [comment]
It is still present in OSX version.

**Comment by chrisburton** [comment]
Still present for me also in OS X Yosemite.
