### ISSUE TITLE
Unable the install the program

### ISSUE THREAD

**Issue by xXxSniparxXx96** [FlixtorMe/FlixtorMe#26]
I try to install the new version of Flixtor but I get this error.
"
Unable to execute file in temporary directory. Setup aborted.

Error 5: access is denied.
"
I tried to change the location and run it as admin.

**Comment by FlixtorMe** [comment]
@xXxSniparxXx96 did you have a previous version of flixtor installed before you reinstall?

**Comment by xXxSniparxXx96** [comment]
again, I did have previous version installed but I removed it when it wouldnt install the new one. Previous versions have still installed even if I've had earlier version of Flixtor.

**Comment by FlixtorMe** [comment]
We will take a look on this issue and response as fast as possible

**Comment by FlixtorMe** [comment]
Plesse try the following steps:

- Completly uninstall flixtor
- remove flixtor folder under <USERNAME>\AppData\Local\
- reinstall latest flixtor version

**Comment by xXxSniparxXx96** [comment]
I removed all traces of Flixtor and removed the Local folder but it still it whines the same thing. Can I try to download earlier version of Flixtor? if so, where?

**Comment by FlixtorMe** [comment]
Not yet, we will try to send you an earlier version of flixtor. Previous version worked fine, right?

**Comment by xXxSniparxXx96** [comment]
Yes I had no problem installing it.

**Comment by FlixtorMe** [comment]
@xXxSniparxXx96 please test our latest flixtor release

**Comment by xXxSniparxXx96** [comment]
Not working.

**Comment by FlixtorMe** [comment]
@xXxSniparxXx96 we uploaded a version without the installer. Please try this download https://flixtor.me/download/Flixtor_win.zip

**Comment by xXxSniparxXx96** [comment]
Well not it works but it takes very long time to launch :) That will do for now tyvm.
