### ISSUE TITLE
Can't load plugin (windows 8.1)

### ISSUE THREAD

**Issue by Zanatus** [FlixtorMe/FlixtorMe#27]
Don't know why but he cant load the vlc plugin, i got win8.1 vlc's lastest version with full features installed, i see it on the folder C:/Programs x86/VideoLan/VLC/npvlc.dll but I always get the error on getting external player because internal one doesn't work...
Nice project, got my point in favor! ;)

**Comment by FlixtorMe** [comment]
@Zanatus please test our latest flixtor release
