### ISSUE TITLE
Chromecast on Android not stable

### ISSUE THREAD

**Issue by Ilfalco87** [FlixtorMe/FlixtorMe#33]
Having problems here when connecting to Chromecast. Sometimes it manages to establish a connection, but after a few minutes, it's broken. Other times nothing happens at all. I'm on Android 4.4, on a Oneplus One.

**Comment by FlixtorMe** [comment]
We are aware of this problem. Hope to get it fixed in new version

**Comment by FlixtorMe** [comment]
New android app available!
We are proud to announce that a new version of our android app is available. Check out https://flixtor.me
