### ISSUE TITLE
broken and slow

### ISSUE THREAD

**Issue by esdf** [FlixtorMe/FlixtorMe#34]
I've got a few issues with 2.2.3, it loads slow, browses movies slow and torrents tab ain't even working. Now I think I know why torrents tab is not working, it's because you haven't updated the source in js/kickasstorrents/kickasstorrents.js which should be kickass.to, not .so, but for the overall dcrease in speed i've no clues.

edit: grabbed the source and fixed it, works good now, but it's missing cover images on tv shows

**Comment by FlixtorMe** [comment]
New release is available in the next 30min ;)

**Comment by FlixtorMe** [comment]
Fixed
