### ISSUE TITLE
the subtitles on the android does not work

### ISSUE THREAD

**Issue by rdashorst** [FlixtorMe/FlixtorMe#35]
The subtitles on the Android app unfortunately does not work. Comes or is a solution for this?

**Comment by FlixtorMe** [comment]
Please give us some information. Android version, movies or series or both? Flixtor version?

**Comment by rdashorst** [comment]
Both of them don't work.
And streaming via cromecast is very unstable .After 2 minutes, he always pops out

Flixtor versie. 0.12

Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: FlixtorMe <notifications@github.com>
Datum: 02-03-2015  18:15  (GMT+01:00)
Aan: FlixtorMe/FlixtorMe <FlixtorMe@noreply.github.com>
Cc: rdashorst <rdashorst@hotmail.com>
Onderwerp: Re: [FlixtorMe] the subtitles on the android does not work (#35)

Please give us some information. Android version, movies or series or both? Flixtor version?

---

**Comment by FlixtorMe** [comment]
New Android APP will be released tomorrow 12 april

**Comment by FlixtorMe** [comment]
New android app available!
We are proud to announce that a new version of our android app is available. Check out https://flixtor.me
