### ISSUE TITLE
the app doesn´t work on intel based android systems

### ISSUE THREAD

**Issue by wasabini** [FlixtorMe/FlixtorMe#36]
Hi there!! 

Great app!! love it to watch tv shows in my language. But im having a problem using the android box tv Minix Neo Z64 android 4.4.4 kitkat based. it keeps loading but doesn´t start! On my android phone (bq e4.5) it works as it should be... is this some problem with the intel atom chip? the minix x8h plus works well with the flixtor app (the chipset is different, an amlogic) another problem i've encounter was that movies aren´t appearing on the app(desktop and android app), only tv shows.

thanks hope you keep this excellent app growing!! Congrats!!

**Comment by FlixtorMe** [comment]
We didn't support Android TV boxes at the moment
