### ISSUE TITLE
Unable to load movies on Android.  Only Series

### ISSUE THREAD

**Issue by kylesm87** [FlixtorMe/FlixtorMe#37]
The application appears to launch fine by all accounts, and I'm currently watching Game of Thrones and it's casting to my TV beautifully.  But I can't see any movies listed, can't search for any, nothing.  No options or anything either.  Thanks.

**Comment by gilly65** [comment]
Same here, the app says there's an update available (Android), but no idea where or how to get it...

**Comment by TheDogJones** [comment]
I forked the code and looked through it.  The code on this GitHub is only for the desktop app, so I don't know if anything here applies to Android.  :(

**Comment by FlixtorMe** [comment]
New Android APP will be released tomorrow 12 april

**Comment by LyuboA** [comment]
Same problem here nothing in movie section its 14th android app says update available but where do we get it website download section hold the old one

**Comment by b-reezy** [comment]
Any news on the Android app?

**Comment by TheDogJones** [comment]
No.  I have offered to fix it myself, but they just wanted me to add more features to the Windows app.  They won't give access to the Android code.

**Comment by FlixtorMe** [comment]
Sorry for the delay. We will upload the latest android version soon

**Comment by FlixtorMe** [comment]
New android app available!
We are proud to announce that a new version of our android app is available. Check out https://flixtor.me
