### ISSUE TITLE
not working on blackberry z10? help please. 

### ISSUE THREAD

**Issue by tares003** [FlixtorMe/FlixtorMe#39]
Hi flixtor, 
Its not working for me I am using blackberry z10 android version 4.3. Everything loads but when I press play I get "loading..." . I have waited 20 minutes notting happened it's the same screen. Please help thank you

**Comment by FlixtorMe** [comment]
The blackberry z10 seems to be an special case. Its not an real android device and blackberry also say that not all android applications run fine on that device. 
I will also test it again on an real android device with android 4.3, but i reckon we can not help you.

**Comment by tares003** [comment]
So it wouldn't work on android 4.3?

**Comment by FlixtorMe** [comment]
I tested it with android 4.3 on a real android. Everythings is working correctly. It seems to be an problem with the blackberry z10, there isn't running an real android. Its an known issue that not all native android apps running on this device. Sorry but we only support "real" android devices at the moment
